### PR TITLE
Tooling Improvements

### PR DESCRIPTION
**Pull request by sgammon**
## Summary

Adds more project documentation and prepares for full BCR support.

### Constituent PRs

- #8 
- #7 

### Task list

- [x] Working Bzlmod sub-module test
- [x] CI improvements
- [x] **Docs**
  - [x] DCO, CLA, PR template
  - [x] Contribution guide
  - [x] Security policy
  - [x] README improvements
  - [x] Copy-paste samples updated
  - [x] Actions job for deploying docs site
- [x] **BCR Support**
  - [x] Config files for module publish
- [x] **Tooling**
  - [x] Dependency review
  - [x] Support for Bazel CI
  - [x] Dependabot
  - [x] Renovate
  - [x] CodeQL
  - [x] OpenSSF Scorecard
  - [x] Hardened CI
  - [x] Linting
  - [x] ~~Support for full-blown integration tests~~ _note: next pr_
  - [x] Release flow for BCR

## Changelog

- feat: add bazel ci presubmit
- test: run integration test for bzlmod in ci
- chore: add contribution guide
- chore: readme updates
- chore: doc link fixes
- chore: add CLA, DCO docs
- chore: add PR template
- chore: add dependency review config
- chore: drop outdated travis config
- chore: readme updates

### CODE REVIEW

**Comment by alexeagle** [comment]
Hey, you should check out https://github.com/bazel-contrib/publish-to-bcr/ for the actual publish step, so that every release gets automatically published to the registry.

**Comment by sgammon** [comment]
@alexeagle heya :) will do -- should i set that up before i get approved on the BCR PR?

**Comment by alexeagle** [comment]
I generally do it from the beginning, following https://github.com/bazel-contrib/rules-template
If you do a manual publish, it's just delaying the release where you work out the automation.

**Comment by sgammon** [comment]
nice 👍🏻 caught me just in time, and on the perfect PR too. I'll add the `.bcr` configs and get the action going. I figured I'd have to be approved before I could push.

**Pull request merged**
