### PR TITLE
fix: avoid using deprecated ctx.resolve_tools

### LINKED ISSUE #458: Migrate for --incompatible_disallow_ctx_resolve_tools
See https://github.com/bazelbuild/bazel/issues/22249

Usage in this repo: 
https://github.com/sgammon/rules_graalvm/blob/986584552f9e08f88e03624a0a29063993447259/internal/native_image/rules.bzl#L61-L63

[rules_graalvm](https://github.com/sgammon/rules_graalvm) is used by Bazel itself, so this is blocking building Bazel with Bazel@HEAD (or upcoming Bazel 8.0).

### PR DESCRIPTION
**Pull request by tjgq**
See https://github.com/bazelbuild/bazel/issues/22249 for context.

Fixes #458.

### CODE REVIEW

**Review by sgammon — APPROVED** [review]

**Comment by meteorcloudy** [comment]
@sgammon Are we getting a new release anytime soon? For now, Bazel has to patch rules_graalvm to make sure we can upgrade to Bazel 8: https://github.com/bazelbuild/bazel/blob/aa397cf37d7d013740b4081c19bef38b992b3eab/MODULE.bazel#L64-L69, other users probably have to do the same.

**Comment by sgammon** [comment]
@meteorcloudy IIRC release couldn't happen last time it was attempted (at least at the latest version of GraalVM) because of unstable download URLs. those may have been fixed now, so it's worth a retry.

is the patch above applied because there hasn't been a release to BCR, or because there hasn't been a release in general? If it's sufficient to release to the GH repo only, that can be very quick

**Comment by meteorcloudy** [comment]
> because of unstable download URLs.

We can skip this check on BCR presubmit.

> is the patch above applied because there hasn't been a release to BCR

Yes, ideally there should be a new version on BCR containing this fix.

**Comment by meteorcloudy** [comment]
See the same breakage of rules_graalvm in https://github.com/bazelbuild/bazel-central-registry/issues/3260

**Comment by sgammon** [comment]
@meteorcloudy In this case the unstable download URLs were GraalVM's own URLs... unless that's what you mean? I do think they have likely fixed them now (we needed at least one `23.x` point-release so that the archive URLs exist, and I believe that has taken place).

I'm out for the holiday today but I can take this on once I'm back (probably Sun or Mon). Thanks for your patience and for explaining.

**Comment by meteorcloudy** [comment]
No worries, Bazel itself is fine for now, I'm just worried other rules_graalvm might hit this after Bazel 8 release (which will happen next week). Thanks for taking a look!

**Pull request merged**
