### PR TITLE
fix: update skylib to fix Bazel version check for dev builds instead

### PR DESCRIPTION
**Pull request by fmeum**
This reverts commit 3b204f7ee3e756e477d0cb77cae04d89c457cd7d and instead resolves the problem by updating skylib.

### CODE REVIEW

**Comment by fmeum** [comment]
@sgammon Not sure what's up with the macOS build, looks like some kind of authentication failure.

**Comment by sgammon** [comment]
@fmeum could be our build cache? I've updated my key; let me try a re-run.

**Comment by fmeum** [comment]
@sgammon Thanks, tests are passing now.

**Review by sgammon — APPROVED** [review]

**Comment by sgammon** [comment]
Sounds good. Feel free to merge when ready.

**Pull request merged**
